version: '3.7'

volumes:
   petwallet_db_volume:
        
services:
    db:
        image: "postgres:12"
        env_file: ./pet-wallet-db.env
        container_name: pet-wallet-db
        ports:
            - "5432:5432"
        restart: on-failure
        volumes:
            - petwallet_db_volume:/data/postgres
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
            
    backend:
        build: ./service
        env_file: ./pet-wallet-backend.env
        container_name: pet-wallet-backend
        links:
            - "db:db"
        ports:
            - "8080:8080"
        restart: on-failure
            
networks:
  default:
    driver: bridge